### PR TITLE
ERL-212: add nemos-images-reference-mantic and nemos-images-minimal-mantic images

### PR DESCRIPTION
**Pull request by IsaacJT**
Add new images for all platforms based on Ubuntu 23.10 Mantic

### CODE REVIEW

**Comment by IsaacJT** [comment]
@m-kat @ahresse this is now ready for review

**Comment by ahresse** [comment]
Do we need dracut to force to get parport drivers because I notified:
```
ctx=0x55f549dd6ad0 path=/lib/modules/5.15.0-1017-s32-eb/kernel/drivers/parport/parport.ko error=No such file or directory
```

However, we have: `CONFIG_PARPORT=m` 

?

**Comment by ahresse** [comment]
Aside the missing `-x` flag avoider patch for busybox that need to be applied, the rest seems ok for me.

**Comment by IsaacJT** [comment]
> Do we need to force dracut to get parport drivers because, on qemu_amd64 I notified:

I don't think we need to worry about that - that's the parallel port driver, and we don't need (or have any) parallel interfaces.

> Aside the missing -x flag avoider patch for busybox that need to be applied, the rest seems ok for me. (Only tested on qemu_amd64)

The busybox fix is now building in the PPA

**Review by ahresse — APPROVED** [review]

**Review by m-kat — APPROVED** [review]

**Pull request merged**
