### PR TITLE
Add new NemOS reference image

### PR DESCRIPTION
**Pull request by IsaacJT**
These commits add a new reference image which can (or will be able to) demonstrate all of the advanced features of the NemOS system. This image will be considerably different and have different goals to the existing "embedded" image, which is mostly targetted at small systems without any additional configuration or packages. 

The new features include:
* `dm-verity`
* `dm-integrity`
* multiple mounted filesystems
* xfs support
* squashfs root filesystem with a persistent read/write overlay partition
* EFI boot support
* the addition of a "development" build profile which adds snapd (support TBD) and apt support

### CODE REVIEW

**Comment by IsaacJT** [comment]
Still WIP - need to update the README. PR opened for preliminary review by @schaefi

**Comment by IsaacJT** [comment]
I guess it depends on what we want to do with the image. My intention was essentially to create an image with all the bells and whistles turned on as a bit of a showcase for everything.  You're right that it's more "embedded-like" as no one would actually use it in this constellation of settings.

**Comment by IsaacJT** [comment]
Still facing one issue race condition when combining dm-verity and dm-integrity on the root mount. Working on that now

**Comment by IsaacJT** [comment]
Confirmed working with latest version of `dracut-kiwi-verity` from the NemOS PPA

**Comment by schaefi** [comment]
@IsaacJT pretty cool and sort of a crazy setup right :) So we have root on squashfs (ro) mapped through dm-verity (which from the beginning on I thought is kind of a duplicate thing, but ok some hacker could exchange blocks inside the squashfs with low level access. But then such an attacker could also recreated the verityhash). That device is no overlay mapped into a copy on write region which you mapped through dm-integrity if I understood it correctly. So we have double writes through overlayfs on each block write to check the integrity.

Now let's add crypt on top of dm-integrity :-))

This setup is insanely genius. I think you might want to add some description in the readme to describe the flow of data. A simple diagram would be cool.

Please drop the WIP label if you think we are ready to merge. Thanks much

**Comment by IsaacJT** [comment]
> pretty cool and sort of a crazy setup right 

Totally :D

> (which from the beginning on I thought is kind of a duplicate thing, but ok some hacker could exchange blocks inside the squashfs with low level access. But then such an attacker could also recreated the verityhash

I was thinking about this as well and it actually does make sense, as `dm-verity` doesn't just do a checksum/hash, it also cryptographically checks the image (in this build it's just a snakeoil certificate, but in a production use-case you'd use an actual private key).

> That device is now overlay mapped into a copy on write region which you mapped through dm-integrity if I understood it correctly. So we have double writes through overlayfs on each block write to check the integrity.

Correct :)

> Now let's add crypt on top of dm-integrity :-))

Right, that's my next goal. Although as far as I understand `dm-integrity` was specifically made to work with `dm-crypt`, so it should all work together nicely.

> This setup is insanely genius. I think you might want to add some description in the readme to describe the flow of data. A simple diagram would be cool.

I think so too - I will add some documentation tomorrow morning and push it, then we can close this.

**Comment by IsaacJT** [comment]
Btw these are the two repos for the tool and module I made for running inside Dracut to parse the verity metadata and map the device:

https://git.launchpad.net/~nemos-team/nemos/+git/kiwi-parse-verity/tree/?h=main
https://git.launchpad.net/~nemos-team/nemos/+git/dracut-kiwi-verity/tree/?h=main

These are also init-system independent, so systemd isn't required.

It would be cool to get these published somewhere for other people to use with Kiwi (I guess it should also work outside of Ubuntu). Maybe we can get them into the main Kiwi repo?

**Comment by schaefi** [comment]
> Btw these are the two repos for the tool and module I made for running inside Dracut to parse the verity metadata and map the device:
> 
> https://git.launchpad.net/~nemos-team/nemos/+git/kiwi-parse-verity/tree/?h=main https://git.launchpad.net/~nemos-team/nemos/+git/dracut-kiwi-verity/tree/?h=main
> 
> These are also init-system independent, so systemd isn't required.
> 
> It would be cool to get these published somewhere for other people to use with Kiwi (I guess it should also work outside of Ubuntu). Maybe we can get them into the main Kiwi repo?

This is a great idea. I will create a branch in the kiwi project and prepare it in a way that it meets the structure for dracut modules provided with kiwi. I will copy the code from your project over to the branch and let you know when I'm done. You can then take over the branch and finalize it for a pull request because all Kudos should go to you :) You will need write permissions on the kiwi project which I would be very happy if you accept. Sounds like a plan ?

**Comment by IsaacJT** [comment]
Great - that sounds perfect! 

I'll work on getting `kiwi-parse-verity` into the Debian/Ubuntu archives in the meantime.

**Comment by schaefi** [comment]
> Great - that sounds perfect!

ok cool. Please find:

* https://github.com/OSInside/kiwi/tree/dracut_kiwi_verity

I did some changes:

- minor changes on the code to make linters and shellcheck happy
- added rust vendoring
- included module code to be packaged in the way upstream does it. Once this is merged I need to talk to Adrian (Upstream debian maintainer to update the debian/ instructions regarding this change)

I'll add you to the kiwi project now, really much appreciated. Thanks a ton

Feel free to take over the branch as you see fit

**Comment by IsaacJT** [comment]
Looks great - thanks.

I was thinking that maybe it would be better to move `kiwi-parse-verity` into the /tools directory so that it could be built separately and maybe as its own .deb package. It would definitely make it easier to get into the Debian/Ubuntu archives if it's just a package under the Kiwi umbrella

**Comment by schaefi** [comment]
> I was thinking that maybe it would be better to move `kiwi-parse-verity` into the /tools directory so that it could be built separately and maybe as its own .deb package (or just in `kiwi-tools`?). It would definitely make it easier to get into the Debian/Ubuntu archives if it's just a package under the Kiwi umbrella

I think it is done that way. The ```dracut/modules.d/80kiwi-verity``` is packaged up into its own sub-package named
```dracut-kiwi-verity```. For details see: ```package/python-kiwi-spec-template```. I intentionally did not put ```kiwi-parse-verity``` into the tools area because this tool is only useful in the scope of dracut and the ```kiwi-verity``` module. Thus I thought it would be good to provide it as such in a dracut module package. Please note the upstream packaging of kiwi uses a concept called **debbuild** which creates .deb packages out of an rpm .spec file when building in the open buildservice. That way I can serve debian distros also with packages but of course those are not the ones accepted by the Debian community.

For that part I will contact Adrian as the Debian maintainer for the kiwi package in the Debian community, as he will then adapt the ```debian/...``` data to build that sub-package in a Debian acceptable way.

I think we only need to agree if the concept of producing a ```dracut-kiwi-verity``` package providing the dracut module code and the tools is ok ?

From my perspective it is as we follow this style for all the other dracut-kiwi-* packages

Thoughts ?

**Comment by IsaacJT** [comment]
I've updated the README with some more information about the storage architecture. Unfortuantely I can't remove the WIP label myself, but it should be ready for merging now.

**Comment by IsaacJT** [comment]
> I think we only need to agree if the concept of producing a dracut-kiwi-verity package providing the dracut module code and the tools is ok ?

That sounds perfect - I think we'd be very happy with that. It seems like the most logical solution.

**Comment by IsaacJT** [comment]
I'll add `dm-crypt` support in a future PR ;)

**Comment by schaefi** [comment]
> I've updated the README with some more information about the storage architecture. Unfortuantely I can't remove the WIP label myself, but it should be ready for merging now.

You should have all permissions now. Thanks for the hard work

**Comment by schaefi** [comment]
@IsaacJT is the number of commits ok as a logical set, or do you want to re-organize/squash them ?

**Comment by IsaacJT** [comment]
Good point - I squashed them and remove the podman commit as that is still very much a WIP and there's not much point in adding it now.

**Pull request merged**
