### PR TITLE
Use dracut module for overlay

### PR DESCRIPTION
**Pull request by schaefi**
Enable overlayfs (temporary writing) for the x86_64 and aarch64 images using the kiwi dracut overlay module

### CODE REVIEW

**Comment by schaefi** [comment]
@IsaacJT this PR has some downsides that we need to discuss first:

1. I could not meet the 128MB size limit anymore since kernel and initrd were growing. I moved to 256M and I think for the matter of this project it's fine. There is a chance that we get down to 128MB if Kuba finished the kernel work. So I'm ok with increasing the size, I think there will be nobody complaining anyway. Thoughts ?

2. kiwi provides overlay support for disk image via the package ```dracut-kiwi-overlay```. This is usually a sub package of the kiwi packaging on Debian. See an older build here: https://build.opensuse.org/package/show/home:marcus.schaefer/kiwi-debian. However, on Lunar I was not able to find this package which forced me to add another repository entry using the package from an upstream build of the buildservice and for an older distro too. That part we have to fix prior merging imho

Thanks

**Comment by IsaacJT** [comment]
`dracut-kiwi-overlay` is present in Lunar: https://packages.ubuntu.com/lunar/kiwi-dracut-overlay

I had a play around with this but ran into a lot of trouble with the shell scripts being bash-specific, and I then had to add bash everywhere. Do you have another version with busybox/dash-compatible scripts?

**Comment by IsaacJT** [comment]
Did you get a chance to have a look at the script I made?  It's basically just a slightly modified version of the builtin dracut module for doing tmpfs over overlayfs: https://git.launchpad.net/~itrue/nemos/+git/dracut-overlay-root-persistent/tree/overlay-mount.sh?h=main

It doesn't solve the issue for initrd-less systems, but it's a dash-compatible and small-footprint way to mount the FS's

**Comment by schaefi** [comment]
> I had a play around with this but ran into a lot of trouble with the shell scripts being bash-specific, 

you only need to add ```add_dracutmodules+=" bash "``` as I did in this pull request to fix this. The code from the dracut module can actually be easily ported, it only complains because I use the ```function foo {``` notation

**Comment by schaefi** [comment]
> dracut-kiwi-overlay is present in Lunar: https://packages.ubuntu.com/lunar/kiwi-dracut-overlay

Hmm, ok so why is it not found in the current repository configuration.... strange

**Comment by IsaacJT** [comment]
> it only complains because I use the function foo { notation

And about usage of `declare` - but good to know that it's alright for us to have bash in the initrd. For some reason I had that in my mind that bash was to be avoided (I guess just on the rootfs?)

> Hmm, ok so why is it not found in the current repository configuration.... strange

Might be because of the naming scheme. It's called `kiwi-dracut-overlay` in the archives, rather than `dracut-kiwi-overlay` (as it stems from the `kiwi` package)

**Comment by schaefi** [comment]
Ah I'm so stupid the package name is different ```kiwi-dracut-overlay``` on Debian ```dracut-kiwi-overlay``` on suse/fedora...

**Comment by schaefi** [comment]
> For some reason I had that in my mind that bash was to be avoided (I guess just on the rootfs?)

yeah the message send here was "no scripts" but as soon as you are talking about dracut there are scripts all over the place in the initrd. Whether they are evaluated by dash, ash, bash, zsh ;) I think is immaterial.

If I understood Jens and others correctly the driver for "no scripts" was in the target (rootfs) system such that it is not possible to let anybody interpret any kind of code.

So from my perspective we are not violating that goal as long as we are in the initrd which also only exists temporary for booting up the system. If possible we should avoid that someone can land in a rescue shell inside of the initrd, but that's a different story imho

**Comment by schaefi** [comment]
how surprising, changing the name of the package to the right name and it works :)

**Comment by schaefi** [comment]
> Did you get a chance to have a look at the script I made? It's basically just a slightly modified version of the builtin dracut module for doing tmpfs over overlayfs: https://git.launchpad.net/~itrue/nemos/+git/dracut-overlay-root-persistent/tree/overlay-mount.sh?h=main
> 
> It doesn't solve the issue for initrd-less systems, but it's a dash-compatible and small-footprint way to mount the FS's

I did not had a chance to look at it as I wanted to finish the change to make it work with the kiwi provided module.

I think the best situation around dracut modules is, if you have them upstream in dracut. We did that lately with the dmsquash module to allow persistent writing for live ISOs which was the only bit missing. The overlay module for disk images is still something we would like to get upstream in dracut.

I'm sure your module will also do the job. If we want to use this one rather than the one delivered with kiwi itself we need to bring back the disablement of the overlay runtime check and install your module plus an ```add_modules``` setup in the overlay files.

I don't have a strong opinion but from a maintenance perspective the kiwi overlay module is maintained as part of the opensource project and maybe the natural choice as long as there is no 1:1 substitute on dracut upstream

Thoughts ?

**Comment by schaefi** [comment]
> I'm a bit concerned by the amount of scripts that determine the partition UUIDs

I disliked that either and it's the result of messages like "there will be no udev", "there will be no systemd",
"there will be no initrd". That puts you back to non-persistent unix device nodes :/ In the images here we
seem to deviate from that messages and EB seems to be fine with it according to what Jens said in yesterdays
meeting when he agreed to basically all your point.

So this allows also to use kiwi in a nicer way and I have created a commit for the x86 image to change
the following there:

* Use grub tooling to create grub config
* Use kiwi's support for persistent device handling
* Build a hybrid EFI/CSM style image

So your issue regarding ID scripts should be solved on the x86 side of things. Also the image can now
boot up via:

```
kvm -drive file=nemos-image-embedded-lunar.x86_64-1.0.1.qcow2,if=virtio
kvm -bios /usr/share/qemu/ovmf-x86_64-ms.bin -drive file=nemos-image-embedded-lunar.x86_64-1.0.1.qcow2,if=virtio
```

in both firmware worlds

**Comment by schaefi** [comment]
On the aarch64 side however there is no "uboot tooling to create a config file" and at that level I would leave things as they are right now

**Comment by schaefi** [comment]
@IsaacJT If this matches your expectations would be great if you can review the PR here. Thanks a ton

**Review by IsaacJT — APPROVED** [review]
Thanks - LGTM!

**Comment by schaefi** [comment]
Thanks and pushed to launchpad

**Pull request merged**
