### PR TITLE
ERL-265: nemos-images-reference-lunar: *: add auditd

### PR DESCRIPTION
**Pull request by IsaacJT**
This provides a mechanism for capturing system events to the log.

### CODE REVIEW

**Comment by schaefi** [comment]
Just to mention that EB implements its own messaging service called ```elos```, done by Emlix which they also want to opensource. In case we want to stay a little bit inline with tools used at EB side I just wanted to mention it. Clarification on this part should be imho done in a meeting with Bo and Alex. Just my 2cents

**Comment by IsaacJT** [comment]
Welcome back from your well-deserved leave :)

`auditd` mostly focuses on logging events, whereas (as far as I understand) `elos` is more of a complete event manager for the system, so I think they can coexist pretty well on the same system without too much overlap. I'm happy to discuss this further with the rest of the team in the technical meetings, but I will be away for the next few weeks.

**Comment by schaefi** [comment]
> Welcome back from your well-deserved leave :)

Thanks :)

**Comment by schaefi** [comment]
> `auditd` mostly focuses on logging events, whereas (as far as I understand) `elos` is more of a complete event manager for the system, so I think they can coexist pretty well on the same system without too much overlap. I'm happy to discuss this further with the rest of the team in the technical meetings, but I will be away for the next few weeks.

you are right they can co-exist without any problems. It's just a matter of how many log daemons we want to run. afaik with elos the plan is to "cover-them-all" but I might be wrong here.

The change here looks good and can go in without conflicts

All the best for your well deserved breath out :)

**Comment by IsaacJT** [comment]
Yeah that's a good point with how many log daemons we actually need. I'd be happy to pull this in now and revise it again when `elos` is available for us to use and include in the public images.

**Pull request merged**
